### ISSUE TITLE
[Suggestion] - delete project.lock.json

### ISSUE THREAD

**Issue by dazinator** [mperdeck/jsnlog.AspNet5Demo#1]
I have hit this issue in the pastw ith NuGet restore not working, and excluding the `project.lock.json` file from source control fixed it for me, and allows NuGet restore to work in typical fashion. This is something you may want to try. My understanding is that this file should only be committed to source control, when the dependencies / packages are also being committed.

**Comment by mperdeck** [comment]
Thanks for the suggestion! I removed project.lock.json from the project, but it still didn't automatically restore for me. That is, I still had to do the dnu restore.
