### ISSUE TITLE
ASP.NET Core RC2

### ISSUE THREAD

**Issue by dazinator** [mperdeck/jsnlog.AspNet5Demo#2]
I've upgraded from RC1 to RC2, and part of that meant targeting `net452` now instead of `dnx451 / net451`.

I've update my `jsnlog` to latest version `2.17.1` and I have noticed that it no longer compiles, specifically this line:

![image](https://cloud.githubusercontent.com/assets/3176632/15907033/55291670-2db3-11e6-8f85-d33a7f03b229.png)

I think this is because JsnLog doesn't support ASP.NET Core RC2 yet - but could you confirm?

**Comment by mperdeck** [comment]
You're right, I haven't updated JSNLog for ASP.NET Core RC2. Flat out at work.

A pull request to fix this would be appreciated.

**Comment by dazinator** [comment]
Ok I have upgraded this web application to RC2 in a branch (in my fork).

I had to comment out this line:

```
app.UseJSNLog(new LoggingAdapter(loggerFactory), jsnlogConfiguration);

```

Because JsnLog itself needs to be upgraded for RC2. Once that is done we can update JsnLog in the application and add the equivalent line of code back and all should be roses.

Do you want me to submit a PR at this point - and if so should it target master?

**Comment by dazinator** [comment]
PR submitted that upgrades to RTM now that RTM is out.
